/* eslint-disable react-refresh/only-export-components */
import { BookOpenIcon, CpuIcon, FileTextIcon, GiftIcon, LayoutGridIcon, MousePointerClickIcon, SparklesIcon, ZapIcon } from "lucide-react";

export const homeFeaturesData = [
    {
        icon: <MousePointerClickIcon size={28} />,
        title: "Easy to Use",
        desc: "Get things done quickly with simple tools designed for everyone.",
    },
    {
        icon: <ZapIcon size={28} />,
        title: "Fast & Reliable",
        desc: "Get accurate results in seconds without complicated setup.",
    },
    {
        icon: <GiftIcon size={28} />,
        title: "Free to Use",
        desc: "Use our tools as much as you want with no credit card required.",
    },
    {
        icon: <LayoutGridIcon size={28} />,
        title: "Multiple Tools",
        desc: "Access a growing collection of useful tools for everyday tasks.",
    },
    {
        icon: <CpuIcon size={28} />,
        title: "Smart & Powerful",
        desc: "Powerful features packed into clean and easy-to-use tools.",
    },
    {
        icon: <BookOpenIcon size={28} />,
        title: "Helpful Resources",
        desc: "Learn more with practical guides, tips, and tutorials from our blog.",
    },
];

export const homeHowItWorksData = [
    {
        num: "01",
        icon: <LayoutGridIcon size={24} />,
        title: "Choose a Tool",
        subtitle: "Find the right tool for your task",
        desc: "Browse our collection of useful online tools and choose the one you need.",
    },
    {
        num: "02",
        icon: <FileTextIcon size={24} />,
        title: "Enter Your Details",
        subtitle: "Simply provide what the tool needs",
        desc: "Enter your text, URL, file, or other required information and let the tool do the work.",
    },
    {
        num: "03",
        icon: <SparklesIcon size={24} />,
        title: "Get Your Result",
        subtitle: "Get fast, useful results",
        desc: "View your results instantly, use the output, and explore our blog for helpful tips and guides.",
    },
];

export const homefooterLinks = [
    {
        title: "Product",
        links: ["Features", "Pricing", "API", "Browser Extension"],
    },
    {
        title: "Resources",
        links: ["Documentation", "Blog", "SEO Guide", "Support"],
    },
    {
        title: "Company",
        links: ["About Us", "Careers", "Contact", "Press"],
    },
    {
        title: "Legal",
        links: ["Privacy Policy", "Terms of Service", "Cookie Policy"],
    },
];

export const HomeWave = () => (
    <svg className="w-full h-[15vh] min-h-[60px] max-h-[120px]" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28" preserveAspectRatio="none" shapeRendering="auto">
        <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g className="parallax">
            <use xlinkHref="#gentle-wave" x="48" y="0" fill="var(--accent)" opacity="0.05" />
            <use xlinkHref="#gentle-wave" x="48" y="3" fill="var(--accent)" opacity="0.1" />
            <use xlinkHref="#gentle-wave" x="48" y="5" fill="var(--accent)" opacity="0.15" />
            <use xlinkHref="#gentle-wave" x="48" y="7" fill="var(--accent)" opacity="0.2" />
        </g>
    </svg>
);

export const dummyAnalysisData = [
    {
        categories: { seo: 65, performance: 50, accessibility: 85, bestPractices: 70 },
        metaData: {
            title: "Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in",
            description: "Amazon.in: Online Shopping India - Buy mobiles, laptops, cameras, books, watches, apparel, shoes and e-Gift Cards. Free Shipping & Cash on Delivery Available.",
            canonical: "https://www.amazon.in/",
            robots: "",
            ogTitle: "",
            ogDescription: "Amazon.in: Online Shopping India - Buy mobiles, laptops, cameras, books, watches, apparel, shoes and e-Gift Cards. Free Shipping & Cash on Delivery Available.",
            ogImage: "https://m.media-amazon.com/images/I/51HCHFclmmL.jpg",
            twitterCard: "",
            viewport: "",
            charset: "utf-8",
        },
        headings: { h1: 0, h2: 25, h3: 0, h4: 0, h5: 7, h6: 0, h1Texts: [] },
        links: { broken: 0, internal: 350, external: 25, total: 375 },
        images: { total: 229, missingAlt: 10, withAlt: 219 },
        _id: "69fafd289a3aab480dd24147",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://amazon.in/",
        overallScore: 72,
        loadTime: 5032,
        pageSize: 1163453,
        wordCount: 2132,
        status: "completed",
        createdAt: "2026-05-06T08:34:48.581Z",
        updatedAt: "2026-05-06T08:35:24.611Z",
    },
    {
        categories: { seo: 65, performance: 55, accessibility: 60, bestPractices: 80 },
        metaData: {
            twitterCard: "",
            viewport: "",
            charset: "",
            title: "eBay - Export from India | Become a global online seller",
            description: "eBay is a leading global selling platform for online sellers to export products from India and sell globally. Start your global selling journey with eBay today! Low set-up cost | High profitability",
            canonical: "https://export.ebay.com/in/",
            robots: "",
            ogTitle: "eBay - Export from India | Become a global online seller",
            ogDescription: "eBay is a leading global selling platform for online sellers to export products from India and sell globally. Start your global selling journey with eBay today! Low set-up cost | High profitability",
            ogImage: "/_next/static/images/og-image-ebay-9997ef0e03c45b550a3e445b411aa3c7.png",
        },
        headings: { h4: 0, h5: 0, h6: 0, h1: 0, h2: 33, h3: 3, h1Texts: [] },
        links: { broken: 0, total: 0, internal: 131, external: 20 },
        images: { withAlt: 0, total: 26, missingAlt: 6 },
        _id: "69faf680e608e8071d2bd73f",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://ebay.in/",
        overallScore: 72,
        loadTime: 4936,
        pageSize: 352368,
        wordCount: 1191,
        status: "completed",
        createdAt: "2026-05-06T08:06:24.382Z",
        updatedAt: "2026-05-06T08:06:50.481Z",
    },
    {
        categories: { seo: 85, performance: 75, accessibility: 70, bestPractices: 80 },
        metaData: {
            title: "Microsoft – AI, Cloud, Productivity, Computing, Gaming & Apps",
            description: "Explore Microsoft products and services and support for your home or business. Shop Microsoft 365, Copilot, Teams, Xbox, Windows, Azure, Surface and more.",
            canonical: "https://www.microsoft.com/en-us",
            robots: "index, follow",
            ogTitle: "Microsoft – AI, Cloud, Productivity, Computing, Gaming & Apps",
            ogDescription: "Explore Microsoft products and services and support for your home or business. Shop Microsoft 365, Copilot, Teams, Xbox, Windows, Azure, Surface and more.",
            ogImage: "",
            twitterCard: "summary",
            viewport: "width=device-width, initial-scale=1, shrink-to-fit=no",
            charset: "UTF-8",
        },
        headings: { h1: 1, h2: 18, h3: 8, h4: 0, h5: 0, h6: 0, h1Texts: ["Get the ultimate college bundle"] },
        links: { broken: 0, internal: 88, external: 44, total: 132 },
        images: { total: 29, missingAlt: 6, withAlt: 23 },
        _id: "69faf23859140a797168cd5d",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://microsoft.com/",
        overallScore: 75,
        loadTime: 4929,
        pageSize: 454183,
        wordCount: 650,
        status: "completed",
        createdAt: "2026-05-06T07:48:09.000Z",
        updatedAt: "2026-05-06T07:49:09.170Z",
    },
    {
        categories: { seo: 91, performance: 100, accessibility: 90, bestPractices: 90 },
        metaData: {
            title: "Full Stack Web Development Projects with source code - GreatStack",
            description: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
            canonical: "https://greatstack.dev/",
            robots: "",
            ogTitle: "Full Stack Web Development Projects with source code - GreatStack",
            ogDescription: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
            ogImage: "https://greatstack.dev/greatstack_logo.jpg",
            twitterCard: "summary",
            viewport: "width=device-width, initial-scale=1",
            charset: "utf-8",
        },
        headings: { h1: 1, h2: 34, h3: 0, h4: 0, h5: 0, h6: 0, h1Texts: ["Web Development Projects"] },
        links: { broken: 0, internal: 55, external: 4, total: 60 },
        images: { total: 61, missingAlt: 16, withAlt: 45 },
        _id: "69fad6f73b51176579cd75a9",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://greatstack.dev/",
        overallScore: 93,
        loadTime: 2210,
        pageSize: 126438,
        wordCount: 349,
        status: "completed",
        createdAt: "2026-05-06T05:51:51.274Z",
        updatedAt: "2026-05-06T05:53:15.015Z",
    },
    {
        categories: { seo: 80, performance: 100, accessibility: 60, bestPractices: 85 },
        metaData: {
            title: "Browserbase",
            description: "Give your agents access to the whole web.",
            canonical: "https://www.browserbase.com//",
            robots: "",
            ogTitle: "Browserbase",
            ogDescription: "Give your agents access to the whole web.",
            ogImage: "https://cdn.sanity.io/images/yd6zslid/production/150f4783739729cce34cd1a71ecbd63e0a4de5a9-1824x960.png?w=1200&amp;q=85&amp;auto=format&w=1200&h=628&fit=crop&q=60&fm=jpg",
            twitterCard: "",
            viewport: "width=device-width, initial-scale=1",
            charset: "utf-8",
        },
        headings: { h1: 1, h2: 7, h3: 23, h4: 10, h5: 0, h6: 0, h1Texts: ["Browserbase"] },
        links: { broken: 0, internal: 77, external: 15, total: 98 },
        images: { total: 21, missingAlt: 14, withAlt: 7 },
        _id: "69e1f7d91d170e16d40f88df",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://www.browserbase.com/",
        overallScore: 81,
        loadTime: 920,
        pageSize: 155506,
        wordCount: 952,
        status: "completed",
        createdAt: "2026-04-17T09:05:29.350Z",
        updatedAt: "2026-04-17T09:06:32.723Z",
    },
    {
        categories: { seo: 86, performance: 93, accessibility: 83, bestPractices: 100 },
        metaData: {
            title: "Vercel: Build and deploy the best web experiences with the AI Cloud",
            description: "Vercel gives developers the frameworks, workflows, and infrastructure to build a faster, more personalized web.",
            canonical: "https://vercel.com/",
            robots: "index, max-image-preview:large",
            ogTitle: "Vercel: Build and deploy the best web experiences with the AI Cloud – Vercel",
            ogDescription: "Vercel gives developers the frameworks, workflows, and infrastructure to build a faster, more personalized web.",
            ogImage: "https://assets.vercel.com/image/upload/contentful/image/e5382hct74si/4JmubmYDJnFtstwHbaZPev/0c3576832aae5b1a4d98c8c9f98863c3/Vercel_Home_OG.png",
            twitterCard: "summary_large_image",
            viewport: "width=device-width, initial-scale=1, maximum-scale=1",
            charset: "utf-8",
        },
        headings: { h1: 2, h2: 18, h3: 7, h4: 0, h5: 9, h6: 0, h1Texts: ["Build and deploy on the AI Cloud.", "Build and deploy on the AI Cloud."] },
        links: { broken: 0, internal: 114, external: 18, total: 132 },
        images: { total: 49, missingAlt: 7, withAlt: 42 },
        _id: "69e0b571d1621b9576e47c2a",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://vercel.com/",
        overallScore: 91,
        loadTime: 2797,
        pageSize: 921750,
        wordCount: 775,
        status: "completed",
        createdAt: "2026-04-16T10:09:53.689Z",
        updatedAt: "2026-04-16T10:11:05.444Z",
    },
    {
        categories: { seo: 63, performance: 100, accessibility: 100, bestPractices: 100 },
        metaData: {
            title: "Tailwind CSS UI Components & Templates - PrebuiltUI",
            description: "Tailwind CSS UI components and templates for modern web development. Get access to free, responsive and modern Tailwind CSS components to speed up your web development.",
            canonical: "https://prebuiltui.com/",
            robots: "",
            ogTitle: "PrebuiltUI - Free Tailwind CSS Components & UI Templates",
            ogDescription: "Get access to free, responsive and modern Tailwind CSS components to speed up your web development process.",
            ogImage: "https://prebuiltui.com/opengraph-image.png?opengraph-image.09u6fxlvvs1rv.png",
            twitterCard: "summary_large_image",
            viewport: "width=device-width, initial-scale=1",
            charset: "utf-8",
        },
        headings: { h1: 1, h2: 11, h3: 7, h4: 6, h5: 0, h6: 0, h1Texts: ["Explore the Ultimate  Collection of UI Components"] },
        links: { broken: 0, internal: 397, external: 6, total: 403 },
        images: { total: 124, missingAlt: 0, withAlt: 124 },
        _id: "69ddf15f1ec6a4dc0025f4bc",
        userId: "69dcf7cacc98f8daf29ecca3",
        url: "https://prebuiltui.com/",
        overallScore: 91,
        loadTime: 2022,
        pageSize: 263904,
        wordCount: 1097,
        status: "completed",
        createdAt: "2026-04-14T07:48:47.541Z",
        updatedAt: "2026-04-14T07:49:35.291Z",
    },
];

export const dummyWebsiteAnalysis = {
    categories: { seo: 91, performance: 100, accessibility: 90, bestPractices: 90 },
    metaData: {
        title: "Full Stack Web Development Projects with source code - GreatStack",
        description: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        canonical: "https://greatstack.dev/",
        robots: "",
        ogTitle: "Full Stack Web Development Projects with source code - GreatStack",
        ogDescription: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        ogImage: "https://greatstack.dev/greatstack_logo.jpg",
        twitterCard: "summary",
        viewport: "width=device-width, initial-scale=1",
        charset: "utf-8",
    },
    headings: { h1: 1, h2: 34, h3: 0, h4: 0, h5: 0, h6: 0, h1Texts: ["Web Development Projects"] },
    links: { broken: 0, internal: 55, external: 4, total: 60 },
    images: { total: 61, missingAlt: 16, withAlt: 45 },
    _id: "69fad6f73b51176579cd75a9",
    userId: "69dcf7cacc98f8daf29ecca3",
    url: "https://greatstack.dev/",
    overallScore: 93,
    loadTime: 2210,
    pageSize: 126438,
    wordCount: 349,
    status: "completed",
    keywords: [
        { word: "full stack", count: 28, density: 8.02, _id: "69fad74b3b51176579cd75aa" },
        { word: "projects", count: 19, density: 5.44, _id: "69fad74b3b51176579cd75ab" },
        { word: "react js", count: 12, density: 3.44, _id: "69fad74b3b51176579cd75ac" },
        { word: "mern stack", count: 9, density: 2.58, _id: "69fad74b3b51176579cd75ad" },
        { word: "ai", count: 8, density: 2.29, _id: "69fad74b3b51176579cd75ae" },
        { word: "e-commerce", count: 6, density: 1.72, _id: "69fad74b3b51176579cd75af" },
        { word: "next js", count: 5, density: 1.43, _id: "69fad74b3b51176579cd75b0" },
        { word: "saas", count: 5, density: 1.43, _id: "69fad74b3b51176579cd75b1" },
        { word: "pern stack", count: 4, density: 1.15, _id: "69fad74b3b51176579cd75b2" },
        { word: "blog", count: 3, density: 0.86, _id: "69fad74b3b51176579cd75b3" },
    ],
    issues: [
        {
            severity: "warning",
            category: "Accessibility",
            message: "16 images are missing alt text, which harms accessibility and SEO image indexing.",
            recommendation: "Add descriptive alt text to all 16 images to improve accessibility for screen readers and search engine understanding of image content.",
        },
        {
            severity: "warning",
            category: "SEO",
            message: "The page title tag is 65 characters long, which is slightly above the recommended 50-60 character limit.",
            recommendation: "Consider shortening the title tag to ensure it displays fully in search results and maintains optimal click-through rates.",
        },
        {
            severity: "warning",
            category: "SEO",
            message: "The meta description is 142 characters, slightly below the optimal range of 150-160 characters.",
            recommendation: "Expand the meta description slightly to utilize the full character limit, providing more detail and potentially improving click-through rates.",
        },
        {
            severity: "warning",
            category: "Best Practices",
            message: "The page uses one H1 and 34 H2s, but lacks H3-H6 headings, indicating a flat heading structure.",
            recommendation: "Refine the heading structure to create a clearer hierarchy (H1 > H2 > H3, etc.) for better content organization and semantic SEO.",
        },
        {
            severity: "info",
            category: "SEO",
            message: "The page does not explicitly define a robots meta tag.",
            recommendation: 'While the default behavior is index, follow, consider adding an explicit robots meta tag (<meta name="robots" content="index, follow">) for clarity and control.',
        },
        {
            severity: "info",
            category: "SEO",
            message: "While key terms are present, core phrases like 'web development' could have higher density to match user search intent more closely.",
            recommendation: "Naturally integrate 'web development' and related terms into the main content to slightly increase their density and relevance.",
        },
        {
            severity: "info",
            category: "SEO",
            message: "The page contains only 4 external links, which is relatively low.",
            recommendation: "Consider adding more high-quality, relevant external links to authoritative sources to provide additional value to users and signal credibility to search engines.",
        },
    ],
    createdAt: "2026-05-06T05:51:51.274Z",
    updatedAt: "2026-05-06T05:53:15.015Z",
};

export const dummyRankings = [
    {
        _id: "69faedb159140a797168cd5c",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "full stack projects",
        url: "https://greatstack.dev",
        domain: "greatstack.dev",
        currentPosition: 9,
        currentPage: 2,
        bestPosition: 9,
        positionChange: 3,
        active: true,
        lastChecked: "2026-05-06T07:30:52.744Z",
        status: "completed",
        competitors: [
            {
                position: 1,
                url: "https://www.reddit.com/r/FullStack/comments/1rw24f7/the_projects_that_will_get_you_hired_as_a_full/",
                domain: "reddit.com",
                title: "The projects that will get you hired as a Full Stack Web Dev ...",
                snippet: "Try building something that shows decision-making: authentication with edge cases, role-based access, background jobs, rate limiting, proper ...Read more",
            },
            {
                position: 2,
                url: "https://github.com/ZOUHAIRFGRA/100-Project-Ideas-for-Full-Stack-Developers",
                domain: "github.com",
                title: "ZOUHAIRFGRA/100-Project-Ideas-for-Full-Stack-Developers",
                snippet: "https://github.com > ZOUHAIRFGRA > 100-Project-Idea...",
            },
            {
                position: 3,
                url: "https://www.geeksforgeeks.org/blogs/best-full-stack-project-ideas/",
                domain: "geeksforgeeks.org",
                title: "12 Best Full Stack Project Ideas in 2025",
                snippet: "https://www.geeksforgeeks.org > blogs > best-full-stack...",
            },
            {
                position: 4,
                url: "https://www.frontendmentor.io/articles/full-stack-project-ideas",
                domain: "frontendmentor.io",
                title: "12 Full-Stack Project Ideas for Your Portfolio",
                snippet: "https://www.frontendmentor.io > articles > full-stack-pr...",
            },
            {
                position: 5,
                url: "https://www.turing.com/blog/full-stack-project-ideas-for-software-developers",
                domain: "turing.com",
                title: "Twelve Full Stack Project Ideas for 2025",
                snippet: "https://www.turing.com > blog > full-stack-project-ideas...",
            },
            {
                position: 6,
                url: "https://www.youtube.com/playlist?list=PLjwm_8O3suyOFd8LTFqgw9v7MqPNtgINA",
                domain: "youtube.com",
                title: "Full Stack Projects For Final Year Students (10 ... - YouTube",
                snippet: "Build placement ready or Job ready project using React JS, MongoDB, Express and Node JS. Step by step MERN Stack project for final year students.Read more",
            },
            {
                position: 7,
                url: "https://www.bosscoderacademy.com/blog/best-full-stack-projects-with-source-code",
                domain: "bosscoderacademy.com",
                title: "Top 15 Full Stack Projects with Source Code in 2026",
                snippet: "https://www.bosscoderacademy.com > blog > best-full-st...",
            },
            {
                position: 8,
                url: "https://medium.com/@shivashanker7337/10-full-stack-project-ideas-that-will-actually-get-you-hired-f1ec7fc78433",
                domain: "medium.com",
                title: "10 Full Stack Project Ideas That Will Actually Get You Hired",
                snippet: "",
            },
            {
                position: 10,
                url: "https://www.quora.com/What-projects-do-you-recommend-me-to-do-as-a-full-stack-developer-to-put-on-my-portfolio",
                domain: "quora.com",
                title: "What projects do you recommend me to do as a full-stack ...",
                snippet: "",
            },
            {
                position: 11,
                url: "https://www.theodinproject.com/paths/full-stack-javascript",
                domain: "theodinproject.com",
                title: "Full Stack JavaScript",
                snippet: "https://www.theodinproject.com > paths > full-stack-jav...",
            },
        ],
        createdAt: "2026-05-06T07:28:49.108Z",
        updatedAt: "2026-05-06T07:30:52.745Z",
        __v: 3,
    },
    {
        _id: "69faeb22c92887355e43fef3",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "web development full stack project",
        url: "https://greatstack.dev",
        domain: "greatstack.dev",
        currentPosition: 9,
        currentPage: 2,
        bestPosition: 9,
        positionChange: 0,
        active: true,
        lastChecked: "2026-05-06T07:18:32.603Z",
        status: "completed",
        competitors: [
            {
                position: 1,
                url: "https://www.reddit.com/r/django/comments/1jf46lw/can_someone_suggest_a_good_full_stack_web/",
                domain: "reddit.com",
                title: "Can someone suggest a good full stack web development ...",
                snippet: "I'm currently working on improving my portfolio and looking to build a solid full-stack web development project that I can showcase on my resume.Read more",
            },
            {
                position: 2,
                url: "https://www.geeksforgeeks.org/blogs/best-full-stack-project-ideas/",
                domain: "geeksforgeeks.org",
                title: "12 Best Full Stack Project Ideas in 2025",
                snippet: "https://www.geeksforgeeks.org > blogs > best-full-stack...",
            },
            {
                position: 3,
                url: "https://github.com/topics/full-stack-web-development",
                domain: "github.com",
                title: "full-stack-web-development",
                snippet: "",
            },
            {
                position: 4,
                url: "https://www.frontendmentor.io/articles/full-stack-project-ideas",
                domain: "frontendmentor.io",
                title: "12 Full-Stack Project Ideas for Your Portfolio",
                snippet: "https://www.frontendmentor.io > articles > full-stack-pr...",
            },
            {
                position: 5,
                url: "https://medium.com/@isaac.adams/part-1-from-0-to-1-creating-a-full-stack-web-application-platform-from-scratch-and-operating-it-cd56ed8c2b0a",
                domain: "medium.com",
                title: "From 0 to 1 — Creating a Full-Stack Web Application ...",
                snippet: "",
            },
            {
                position: 6,
                url: "https://aws.amazon.com/what-is/full-stack-development/",
                domain: "aws.amazon.com",
                title: "What is Full Stack Development?",
                snippet: "https://aws.amazon.com > ... > Developer Tools",
            },
            {
                position: 7,
                url: "https://www.theodinproject.com/",
                domain: "theodinproject.com",
                title: "The Odin Project: Your Career in Web Development Starts Here",
                snippet: "Your Career in Web Development Starts Here. Our full stack curriculum is free and supported by a passionate open source community. View Full Curriculum home ...Read more",
            },
            {
                position: 8,
                url: "https://www.bosscoderacademy.com/blog/best-full-stack-projects-with-source-code",
                domain: "bosscoderacademy.com",
                title: "Top 15 Full Stack Projects with Source Code in 2026",
                snippet: "https://www.bosscoderacademy.com > blog > best-full-st...",
            },
            {
                position: 10,
                url: "https://www.turing.com/blog/full-stack-project-ideas-for-software-developers",
                domain: "turing.com",
                title: "Twelve Full Stack Project Ideas for 2025",
                snippet: "https://www.turing.com > blog > full-stack-project-ideas...",
            },
            {
                position: 11,
                url: "https://www.coursera.org/courses?query=full%20stack%20web%20development",
                domain: "coursera.org",
                title: "Full Stack Web Development Courses",
                snippet: "https://www.coursera.org > courses > query=full stack w...",
            },
        ],
        createdAt: "2026-05-06T07:17:54.335Z",
        updatedAt: "2026-05-06T07:18:32.607Z",
        __v: 1,
    },
    {
        _id: "69e0baa3d1621b9576e47c73",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "mern stack project",
        url: "https://greatstack.dev",
        domain: "greatstack.dev",
        currentPosition: 13,
        currentPage: 2,
        bestPosition: 13,
        positionChange: 4,
        active: true,
        lastChecked: "2026-05-06T07:32:00.565Z",
        status: "completed",
        competitors: [
            {
                position: 1,
                url: "https://www.geeksforgeeks.org/mern/mern-stack-projects/",
                domain: "geeksforgeeks.org",
                title: "Top 35+ MERN Stack Project Ideas of 2025",
                snippet: "https://www.geeksforgeeks.org > mern > mern-stack-pr...",
            },
            {
                position: 2,
                url: "https://github.com/topics/mern-stack-project",
                domain: "github.com",
                title: "mern-stack-project",
                snippet: "",
            },
            {
                position: 3,
                url: "https://www.mongodb.com/resources/languages/mern-stack-tutorial",
                domain: "mongodb.com",
                title: "How To Use MERN Stack: A Complete Guide",
                snippet: "https://www.mongodb.com > resources > languages > me...",
            },
            {
                position: 4,
                url: "https://www.reddit.com/r/react/comments/1ohec08/can_anyone_suggest_some_good_projects_to_practise/",
                domain: "reddit.com",
                title: "Can anyone suggest some good projects to practise on ...",
                snippet: "TBH, I enrolled in an offline course to get better with MERN, and I'm only left with Express.js to end, and due to a lack of practice ideas, I'm not confident ...",
            },
            {
                position: 5,
                url: "https://dev.to/devshefali/10-mern-stack-projects-you-should-build-f8c",
                domain: "dev.to",
                title: "10 MERN Stack Projects You Should Build",
                snippet: "https://dev.to > devshefali > 10-mern-stack-projects-you...",
            },
            {
                position: 6,
                url: "https://medium.com/@sindoojagajam2023/setting-up-your-first-mern-stack-project-a-step-by-step-tutorial-0a4f88fa4e98",
                domain: "medium.com",
                title: "Setting Up Your First MERN Stack Project: A Step-by- ...",
                snippet: "If you're new to the MERN stack, this step-by-step tutorial will guide you through setting up your first project.Read more",
            },
            {
                position: 7,
                url: "https://www.youtube.com/playlist?list=PL0Zuz27SZ-6P4dQUsoDatjEGpmBpcOW8V",
                domain: "youtube.com",
                title: "MERN Stack Tutorials",
                snippet: "This MERN Stack playlist builds a complete MERN Stack application from scratch. You will learn about each part of the MERN Stack (MongoDB, Express, React, and ...Read more",
            },
            {
                position: 8,
                url: "https://www.youtube.com/watch?v=1qJwD6mDp48",
                domain: "youtube.com",
                title: "7 Ultimate MERN Stack Projects for 2025 | Source Code + Full ...",
                snippet: "Seven must have projects that every developer needs to build the ultimate portfolio and land on their dream job.",
            },
            {
                position: 9,
                url: "https://www.upgrad.com/blog/mern-stack-project-ideas/",
                domain: "upgrad.com",
                title: "35+ MERN Stack Projects That Impress Recruiters (2026)",
                snippet: "https://www.upgrad.com > Blog > Software Development",
            },
            {
                position: 10,
                url: "https://www.udemy.com/course/mern-stack-project-course-build-fullstack-react-app/?srsltid=AfmBOoqtQ3zNFKq3jZlRB-gzujvZzv2dOO304aM8q0OCFfauirf6Rx5S",
                domain: "udemy.com",
                title: "MERN Stack Project Course - Build Fullstack React App",
                snippet: "https://www.udemy.com > course > mern-stack-project-...",
            },
        ],
        createdAt: "2026-04-16T10:32:03.352Z",
        updatedAt: "2026-05-06T07:32:00.566Z",
        __v: 5,
    },
    {
        _id: "69de4cf7dbad5d2742225431",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "saas tailwind template",
        url: "https://prebuiltui.com",
        domain: "prebuiltui.com",
        currentPosition: null,
        currentPage: null,
        bestPosition: 2,
        positionChange: 0,
        active: true,
        lastChecked: "2026-05-06T09:10:07.409Z",
        status: "completed",
        competitors: [
            {
                position: 1,
                url: "https://tailwindcss.com/plus/templates/salient",
                domain: "tailwindcss.com",
                title: "Salient - Tailwind CSS SaaS Marketing Template",
                snippet: "https://tailwindcss.com > plus > templates > salient",
            },
            {
                position: 2,
                url: "https://tailkits.com/templates/categories/saas/",
                domain: "tailkits.com",
                title: "70+ Tailwind SaaS Website Templates",
                snippet: "https://tailkits.com > templates > categories > saas",
            },
            {
                position: 3,
                url: "https://tailwindcss.com/plus/templates",
                domain: "tailwindcss.com",
                title: "Tailwind CSS Templates - Tailwind Plus",
                snippet: "https://tailwindcss.com > plus > templates",
            },
            {
                position: 4,
                url: "https://saaslandingpage.com/technology/tailwind-css/",
                domain: "saaslandingpage.com",
                title: "SaaS Landing Page Examples Built With Tailwind CSS",
                snippet: "https://saaslandingpage.com > technology > tailwind-css",
            },
            {
                position: 5,
                url: "https://github.com/TailGrids/play-tailwind",
                domain: "github.com",
                title: "Play is free and open source Tailwind CSS template for",
                snippet: "https://github.com > TailGrids > play-tailwind",
            },
            {
                position: 6,
                url: "https://themeforest.net/search/saas%20tailwind?srsltid=AfmBOopwH4rLUfNzMti8CXHZ4mSlWNpAmutKYx7nCPhC6p1pOLd-kMPl",
                domain: "themeforest.net",
                title: "Saas Tailwind Website Templates",
                snippet: "https://themeforest.net > search > saas tailwind",
            },
            {
                position: 7,
                url: "https://adminlte.io/blog/tailwind-business-website-templates/",
                domain: "adminlte.io",
                title: "20 Best Tailwind CSS Templates for Business Websites ...",
                snippet: "https://adminlte.io > Templates",
            },
            {
                position: 8,
                url: "https://www.tailawesome.com/?query=saas&type=template",
                domain: "tailawesome.com",
                title: 'Popular Tailwind templates matching "saas"',
                snippet: "https://www.tailawesome.com > type=template",
            },
            {
                position: 9,
                url: "https://www.reddit.com/r/tailwindcss/comments/1f3ghxh/any_cool_dashboard_recommandations_for_small_saas/",
                domain: "reddit.com",
                title: "Any cool dashboard recommandations for small SaaS on ...",
                snippet: "What is your favourite dashboard template which is free to use and also have really good ui elements? I am looking something exactly for SaaS product, ...",
            },
            {
                position: 10,
                url: "https://tailwindcss.com/showcase",
                domain: "tailwindcss.com",
                title: "Showcase - Build anything",
                snippet: "https://tailwindcss.com > showcase",
            },
        ],
        createdAt: "2026-04-14T14:19:35.731Z",
        updatedAt: "2026-05-06T09:10:07.412Z",
        __v: 5,
    },
    {
        _id: "69dd0cbd0fa79fd71e3b0473",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "greatstack",
        url: "https://greatstack.dev",
        domain: "greatstack.dev",
        currentPosition: 2,
        currentPage: 1,
        bestPosition: 2,
        positionChange: 0,
        active: true,
        lastChecked: "2026-05-06T09:04:47.211Z",
        status: "completed",
        competitors: [
            {
                position: 1,
                url: "https://www.youtube.com/@GreatStackDev",
                domain: "youtube.com",
                title: "GreatStack",
                snippet: "Build placement ready or Job ready project using React JS, MongoDB, Express and Node JS. Step by step MERN Stack project for final year students.Read more",
            },
            {
                position: 3,
                url: "https://github.com/greatstackdev",
                domain: "github.com",
                title: "GreatStack",
                snippet: "https://github.com > greatstackdev",
            },
            {
                position: 5,
                url: "https://www.udemy.com/user/avinash-kumar-202/?srsltid=AfmBOorRj3nv88DzCdZ1eEWOjECXu5OHx91z99rXAiSbuoJ_VgMp77Ch",
                domain: "udemy.com",
                title: "GreatStack by Avinash | Web Development & Digital ...",
                snippet: "https://www.udemy.com > user > avinash-kumar-202",
            },
            {
                position: 6,
                url: "https://www.youtube.com/channel/UCkjoHfkLEy7ZT4bA2myJ8xA/videos",
                domain: "youtube.com",
                title: "GreatStack",
                snippet: "https://www.youtube.com > channel > videos",
            },
            {
                position: 8,
                url: "https://www.youtube.com/watch?v=okGhie_1wPo",
                domain: "youtube.com",
                title: "How To Build Full Stack Social Media Marketplace App Using ...",
                snippet: "In this full stack marketplace project user can buy and sell their social media profiles.",
            },
            {
                position: 9,
                url: "https://in.linkedin.com/company/greatstack",
                domain: "in.linkedin.com",
                title: "GreatStack",
                snippet: "",
            },
        ],
        createdAt: "2026-04-13T15:33:17.509Z",
        updatedAt: "2026-05-06T09:04:47.214Z",
        __v: 3,
    },
    {
        _id: "69dd07c59343d7f693931c97",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "seo tools",
        url: "https://ahrefs.com",
        domain: "ahrefs.com",
        currentPosition: 11,
        currentPage: 1,
        bestPosition: 11,
        positionChange: 0,
        active: true,
        lastChecked: "2026-05-06T09:08:13.422Z",
        status: "completed",
        competitors: [
            {
                position: 1,
                url: "https://smallseotools.com/",
                domain: "smallseotools.com",
                title: "100% Free SEO Tools - SmallSEOTools.com",
                snippet: "You need effective SEO tools which are 100% free? Check out our Search Engine Optimization tools for checking backlinks, tracking keyword positions and ...",
            },
            {
                position: 2,
                url: "https://www.marketermilk.com/blog/best-seo-tools",
                domain: "marketermilk.com",
                title: "24 best SEO tools I'm using in 2026 (free + paid)",
                snippet: "https://www.marketermilk.com > blog > best-seo-tools",
            },
            {
                position: 3,
                url: "https://www.thestate.com/news/business/article315236359.html#:~:text=SEO%20is%20changing%2C%20not%20dying.",
                domain: "thestate.com",
                title: "Is SEO dead in 2026? 7 strategies to thrive in the age of AI | The State",
                snippet: "",
            },
            {
                position: 4,
                url: "https://morningscore.io/simple-and-easy-seo-tools-for-beginners/",
                domain: "morningscore.io",
                title: "The Best Simple SEO Tools for Beginners in 2026 – my opinion",
                snippet: "",
            },
            {
                position: 5,
                url: "https://whatagraph.com/blog/articles/ai-seo-tools",
                domain: "whatagraph.com",
                title: "We Tested the 12 Best (& Underrated) AI SEO Tools in 2026",
                snippet: "https://whatagraph.com > blog > articles > ai-seo-tools",
            },
            {
                position: 6,
                url: "https://www.reddit.com/r/SEO/comments/1148wbc/what_are_the_best_free_seo_tools_to_improve/",
                domain: "reddit.com",
                title: "What are the best free SEO tools to improve website rankings",
                snippet: "One of the best free SEO tools is Google Alerts. This tool allows you to monitor search engine results for specific terms and keywords. By doing ...Read more",
            },
            {
                position: 7,
                url: "https://technicalseo.com/tools/",
                domain: "technicalseo.com",
                title: "SEO Tools",
                snippet: "https://technicalseo.com > tools",
            },
            {
                position: 8,
                url: "https://morningscore.io/best-seo-tools/",
                domain: "morningscore.io",
                title: "The 20 best SEO tools in 2026? I personally tested all tools",
                snippet: "https://morningscore.io > best-seo-tools",
            },
            {
                position: 9,
                url: "https://zapier.com/blog/best-seo-tools/",
                domain: "zapier.com",
                title: "The 11 best SEO tools",
                snippet: "https://zapier.com > App picks > Best apps",
            },
            {
                position: 10,
                url: "https://moz.com/free-seo-tools",
                domain: "moz.com",
                title: "Free SEO Tools by Moz | Try Premium SEO Checkers for ...",
                snippet: "https://moz.com > free-seo-tools",
            },
        ],
        createdAt: "2026-04-13T15:12:05.900Z",
        updatedAt: "2026-05-06T09:08:13.425Z",
        __v: 3,
    },
    {
        _id: "69dd07309343d7f693931c86",
        userId: "69dcf7cacc98f8daf29ecca3",
        keyword: "prebuiltui",
        url: "https://prebuiltui.com",
        domain: "prebuiltui.com",
        currentPosition: 1,
        currentPage: 1,
        bestPosition: 1,
        positionChange: 0,
        active: true,
        lastChecked: "2026-05-06T09:09:20.233Z",
        status: "completed",
        competitors: [
            {
                position: 2,
                url: "https://github.com/prebuiltui/prebuiltui",
                domain: "github.com",
                title: "PrebuiltUI – The Ultimate Collection of UI Components",
                snippet: "https://github.com > prebuiltui > prebuiltui",
            },
            {
                position: 3,
                url: "https://preline.co/",
                domain: "preline.co",
                title: "Preline UI - Free Tailwind CSS UI Components Library",
                snippet: "Preline UI is an open-source Tailwind CSS components library for any needs. Comes with UI examples & blocks, templates, plugins, Figma design system and more.Read more",
            },
            {
                position: 4,
                url: "https://www.instagram.com/prebuiltui/",
                domain: "instagram.com",
                title: "PrebuiltUI",
                snippet: "Whether you're building landing pages, SaaS websites or portfolios - these hero sections give your UI a premium feel instantly. Start exploring: https:// ...",
            },
            {
                position: 5,
                url: "https://www.jsdelivr.com/package/npm/prebuiltui",
                domain: "jsdelivr.com",
                title: "prebuiltui CDN by jsDelivr - A CDN for npm and GitHub",
                snippet: "https://www.jsdelivr.com > package > npm > prebuiltui",
            },
            {
                position: 6,
                url: "https://github.com/prebuiltui",
                domain: "github.com",
                title: "prebuiltui",
                snippet: "PrebuiltUI is a growing collection of beautifully crafted, ready-to-use UI components built with Tailwind CSS. Whether you're creating a landing page, dashboard ...Read more",
            },
            {
                position: 7,
                url: "https://www.reddit.com/r/reactjs/comments/1es2mim/how_do_you_prefer_using_prebuilt_ui_components/",
                domain: "reddit.com",
                title: "How do you prefer using pre-built UI components? : r/reactjs",
                snippet: "I want to provide open-source React UI components for in-app notifications (ie an inbox, notification bell, etc.). Would it be more helpful to go with a shadcn ...Read more",
            },
        ],
        createdAt: "2026-04-13T15:09:36.812Z",
        updatedAt: "2026-05-06T09:09:20.236Z",
        __v: 3,
    },
];

export const dummyWebsiteRanking = {
    _id: "69dd0cbd0fa79fd71e3b0473",
    userId: "69dcf7cacc98f8daf29ecca3",
    keyword: "greatstack",
    url: "https://greatstack.dev",
    domain: "greatstack.dev",
    currentPosition: 2,
    currentPage: 1,
    bestPosition: 2,
    positionChange: 0,
    active: true,
    lastChecked: "2026-05-06T09:04:47.211Z",
    status: "completed",
    rankHistory: [
        {
            date: "2026-05-4T18:30:00.000Z",
            position: 9,
            page: 2,
            title: "GreatStack: Full Stack Web Development Projects with source ...",
            snippet: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        },
        {
            date: "2026-05-05T18:30:00.000Z",
            position: 8,
            page: 2,
            title: "GreatStack: Full Stack Web Development Projects with source ...",
            snippet: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        },
        {
            date: "2026-05-06T18:30:00.000Z",
            position: 5,
            page: 2,
            title: "GreatStack: Full Stack Web Development Projects with source ...",
            snippet: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        },
        {
            date: "2026-05-07T18:30:00.000Z",
            position: 1,
            page: 2,
            title: "GreatStack: Full Stack Web Development Projects with source ...",
            snippet: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        },
        {
            date: "2026-05-08T18:30:00.000Z",
            position: 8,
            page: 1,
            title: "GreatStack: Full Stack Web Development Projects with source ...",
            snippet: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        },
        {
            date: "2026-05-09T18:30:00.000Z",
            position: 6,
            page: 1,
            title: "GreatStack: Full Stack Web Development Projects with source ...",
            snippet: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        },
        {
            date: "2026-05-10T18:30:00.000Z",
            position: 2,
            page: 1,
            title: "GreatStack: Full Stack Web Development Projects with source ...",
            snippet: "Project based learning platform for web developers. Find Full Stack Project, Courses, Tutorial for Next JS, MERN Stack, React JS and HTML-CSS.",
        },
    ],
    competitors: [
        {
            position: 1,
            url: "https://www.youtube.com/@GreatStackDev",
            domain: "youtube.com",
            title: "GreatStack",
            snippet: "Build placement ready or Job ready project using React JS, MongoDB, Express and Node JS. Step by step MERN Stack project for final year students.Read more",
        },
        {
            position: 3,
            url: "https://github.com/greatstackdev",
            domain: "github.com",
            title: "GreatStack",
            snippet: "https://github.com > greatstackdev",
        },
        {
            position: 5,
            url: "https://www.udemy.com/user/avinash-kumar-202/?srsltid=AfmBOorRj3nv88DzCdZ1eEWOjECXu5OHx91z99rXAiSbuoJ_VgMp77Ch",
            domain: "udemy.com",
            title: "GreatStack by Avinash | Web Development & Digital ...",
            snippet: "https://www.udemy.com > user > avinash-kumar-202",
        },
        {
            position: 6,
            url: "https://www.youtube.com/channel/UCkjoHfkLEy7ZT4bA2myJ8xA/videos",
            domain: "youtube.com",
            title: "GreatStack",
            snippet: "https://www.youtube.com > channel > videos",
        },
        {
            position: 8,
            url: "https://www.youtube.com/watch?v=okGhie_1wPo",
            domain: "youtube.com",
            title: "How To Build Full Stack Social Media Marketplace App Using ...",
            snippet: "In this full stack marketplace project user can buy and sell their social media profiles.",
        },
        {
            position: 9,
            url: "https://in.linkedin.com/company/greatstack",
            domain: "in.linkedin.com",
            title: "GreatStack",
            snippet: "",
        },
    ],
    createdAt: "2026-04-13T15:33:17.509Z",
    updatedAt: "2026-05-06T09:04:47.214Z",
    __v: 3,
};
